language: d

sudo: false

d:
  # order: latest DMD, oldest DMD, LDC/GDC, remaining DMD versions
  # this way the overall test time gets cut down (GDC/LDC are a lot
  # slower tham DMD, so they should be started early), while still
  # catching most DMD version related build failures early
  - dmd-2.071.0
  - dmd-2.068.2
  - ldc-1.0.0
  - ldc-0.17.0
  - dmd-2.070.0
  - dmd-2.069.2
